server:
  port: 8882
spring:
  cloud:
    gateway:
      routes:
        - id: limit_route
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/hello/**
          filters:
            - name: CacheBodyFactory
            - name: CustomResponseFilterFactory
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ideKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3

  application:
    name: gateway
  redis:
    host: localhost
    port: 6379
    database: 0